### PR TITLE
fix table in section "Standard OBD fault codes not used by FOME"

### PR DESCRIPTION
**Pull request by mi-hol**

### CODE REVIEW

**Comment by mi-hol** [comment]
@karniv00l @OrchardPerformance for my PRs that **don't change content** (like this one), would it be ok for Piotr to decide about merging them?

**Comment by nmschulte** [comment]
It looks like this change needs applied to all of the rows of this table.

**Comment by mi-hol** [comment]
> It looks like this change needs applied to all of the rows of this table.


Right, I should have elaborated that I'm hunting down the reason for a difference of how tables are displayed in GH versus Docusaurus created webpage (see below). 

It's not clear yet if the fix will work (due to lack of building a temp wiki website), therefore I limited my effort to bare minimum but plan to complete the full doc after the approach is confirmed to work.

Does that approach make sense or did I miss an obvious ability to test Docusaurus ?

GH table:
image

Docusaurus table:
image

**Comment by mi-hol** [comment]
underlying issue captured in https://github.com/FOME-Tech/wiki/issues/135

**Comment by mi-hol** [comment]
I have now fixed all tables so they display  correctly in GH and Docusaurus

**Comment by mi-hol** [comment]
> test Docusaurus by simply

thanks for the hint "how to test a page in Docusaurus".
I've noticed now that a similar hint is (from my perspective hidden) under the title [start-your-site](https://wiki.fome.tech/Quick-page/#start-your-site)

**Review by nmschulte — APPROVED** [review]

**Pull request merged**
