### PR TITLE
make license visible in main project page

### PR DESCRIPTION
**Pull request by mi-hol**

### CODE REVIEW

**Comment by mi-hol** [comment]
fair enough, just fyi, same PR was accepted for rusEFI_documentation repo

**Comment by OrchardPerformance** [comment]
I would say gpl3 is a very not permissive license anyway.
Personally anything I put into the wiki is freely given, speaking for myself I'm happy for it to be used however anyone likes as long as attribution is given.
And that includes withing a commercial or closed use case.

Would be good to get some other views.
Basically to me the wiki is a teaching resource and should be as open as possible.
I just don't like the way V3 prevents the use of assets in another project without polluting it with the GPL. 
I guess that's why speeduino stuck with V2.

**Comment by nmschulte** [comment]
> I just don't like the way V3 prevents the use of assets in another project without polluting it with the GPL.

That's a feature (not a bug).  I'm actually unsure how this would work out legally, like just attribution vs re-license, so can't comment.

Isn't something like a Creative Commons license used frequently for copy/content like this?
https://creativecommons.org/licenses/

**Comment by mck1117** [comment]
> Isn't something like a Creative Commons license used frequently for copy/content like this?
> https://creativecommons.org/licenses/

Yes, that's why I asked about CC. GPL/MIT/Apache/whatever are typically for code, while the various CC options are used for written text works.

**Comment by BeerMoneyMotorsports** [comment]
I do not have an educated opinion on licensing.

**Comment by OrchardPerformance** [comment]
For what its worth, the information governance guys at the council the mrs
now works with suggested one of the creative commons varients

**Comment by mi-hol** [comment]
> suggested one of the creative commons varients

https://chooser-beta.creativecommons.org is a great tool to select the proper license based on input

**Comment by mck1117** [comment]
CC-BY-SA it is.

**Comment by mi-hol** [comment]
Great thanks to all for having the license topic solved!

**Pull request closed without merging**
